---
- name: Ansible Debug Example
  hosts: all
  gather_facts: false
  vars:
    my_variable: "AWX test Github"
  tasks:
    - name: Display a simple message
      debug:
        msg: "Hello AWX"
 
- name: Test connectivity to all hosts
  hosts: all
  tasks:
    - name: Ping all hosts
      ansible.builtin.ping:
